name: AoC check
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "triggered by ${{ github.event_name }}"
      - run: echo "running on ${{ runner.os }}"
      - run: echo "checkout repo ${{ github.repository }} branch ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: |
          yarn install
      - shell: bash
        env:
          AOC_COOKIE: ${{ secrets.aoc_cookie }}
        run: |
          yarn solve 0 1 2015
      - run: echo "status ${{ job.status }}"

